### ISSUE TITLE
Wrong docs?

### ISSUE THREAD

**Issue by futtetennista** [couchand/grunt-envify#1]
The README states that the following should work:

```
grunt.initConfig({
  envify: {
    files: {
      'dest/index.js': ['src/index.js']
    }
  }
});
```

but the correct way to supply files is:

```
grunt.initConfig({
  envify: {
    custom: {
       files: {
         'dest/index.js': ['src/index.js']
       }
    }
  }
});
```

as can be seen in the `Gruntfile`. 

So is this really a problem in the docs or the `files` object should really be inside the `custom` object?

**Comment by couchand** [comment]
Great question.  The docs are basically just the bootstrapped defaults. I don't currently have great access to test this out, but I believe you're right.  Grunt multi-target tasks are generally set up like this, so you can have several different tasks for different parts of the build that use the same plugin and invoke them like `grunt envify:dev` or `grunt envify:production`.  My guess is that's what's going on here.

Like I said, I don't currently have a good setup to test this on (I'm traveling right now), but if you get a chance to verify that this is accurate, feel free to open a PR and I'll merge it in.  Thanks!

**Comment by couchand** [comment]
Looks like your comments are exactly right, @stefanodacchille.  Thanks!

**Comment by futtetennista** [comment]
Glad it was useful ;-)
