### ISSUE TITLE
grunt-envify destroys file

### ISSUE THREAD

**Issue by McOmghall** [couchand/grunt-envify#4]
I currently use this step in my build pipeline: 

```
    envify: {
      prod: {
        files: {
          '<%=distroDir%>client.js': ['<%=distroDir%>client.js']
        }
      }
    }
```

Where distroDir is my dist/ dir. This makes the js file completely dissapear, what might I be doing wrong?

**Comment by couchand** [comment]
It looks like you're trying to use the same filename for the input and output files.  I don't think the Grunt build pipeline will work well if that's what you're intending here, but maybe you meant the input file to use `srcDir` or something.

As an aside, it's not as scalable and more brittle and error-prone to manually stitch together file paths.  You probably want to use Grunt's [dynamic file syntax](http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically).  Something along the lines of:

```
envify: {
  prod: {
    files: {
      expand: true,
      cwd: '<%= srcDir %>',
      src: ['client.js'],
      dest: '<%= distroDir %>'
    }
  }
}
```

**Comment by McOmghall** [comment]
Yeah, I just wanted to make sure `grunt-envify` can overwrite files (I guess it can't). Made it work using a browserify transform though.
